require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Lint/EmptyWhen:
  Enabled: false

Layout/LineLength:
  Enabled: false

# https://github.com/rubocop-hq/rubocop/pull/8692#issuecomment-713772491
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Rails/HasAndBelongsToMany:
  Enabled: false

# https://github.com/rubocop-hq/rubocop-rails/issues/147
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashEachMethods:
  Enabled: false

#TBD:

Rails/HelperInstanceVariable:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
